"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['osx_main.py']
DATA_FILES = ['ndn_app.png', 'static', 'templates']
OPTIONS = {'argv_emulation': True,
           'iconfile': 'ndn_app.icns',
           'includes': [
               'Jinja2',
               'python-socketio',
               'pystray',
               'Pillow',
               'ndncc',
               'aiohttp',
               'aiohttp-jinja2',
               'python-ndn',
               'jinja2.ext',
               ],
           'packages': [
               'Pillow',
           ],
           'plist': {
               'CFBundleIdentifier': "com.ndn.ndncc",
               'CFBundleName': "NDNCC",
               'CFBundleVersion': '1001',
               'CFBundleShortVersionString': '1.0',
               'NSHumanReadableCopyright': 'Copyright 2019 NDN team',
               'LSBackgroundOnly': 'true'
           }
          }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
