# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nfd-face-mgmt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nfd-face-mgmt.proto',
  package='ndn_message',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13nfd-face-mgmt.proto\x12\x0bndn_message\"\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\"\xba\x02\n\x1c\x46\x61\x63\x65\x45ventNotificationMessage\x12\x61\n\x17\x66\x61\x63\x65_event_notification\x18\xc0\x01 \x02(\x0b\x32?.ndn_message.FaceEventNotificationMessage.FaceEventNotification\x1a\xb6\x01\n\x15\x46\x61\x63\x65\x45ventNotification\x12\x18\n\x0f\x66\x61\x63\x65_event_kind\x18\xc1\x01 \x02(\r\x12\x0f\n\x07\x66\x61\x63\x65_id\x18i \x02(\x04\x12\x0b\n\x03uri\x18r \x02(\x0c\x12\x12\n\tlocal_uri\x18\x81\x01 \x02(\x0c\x12\x13\n\nface_scope\x18\x84\x01 \x02(\r\x12\x19\n\x10\x66\x61\x63\x65_persistency\x18\x85\x01 \x02(\r\x12\x12\n\tlink_type\x18\x86\x01 \x02(\r\x12\r\n\x05\x66lags\x18l \x02(\x04')
)




_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='ndn_message.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='ndn_message.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=61,
)


_FACEEVENTNOTIFICATIONMESSAGE_FACEEVENTNOTIFICATION = _descriptor.Descriptor(
  name='FaceEventNotification',
  full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_event_kind', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.face_event_kind', index=0,
      number=193, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_id', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.face_id', index=1,
      number=105, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.uri', index=2,
      number=114, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_uri', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.local_uri', index=3,
      number=129, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_scope', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.face_scope', index=4,
      number=132, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_persistency', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.face_persistency', index=5,
      number=133, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_type', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.link_type', index=6,
      number=134, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ndn_message.FaceEventNotificationMessage.FaceEventNotification.flags', index=7,
      number=108, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=378,
)

_FACEEVENTNOTIFICATIONMESSAGE = _descriptor.Descriptor(
  name='FaceEventNotificationMessage',
  full_name='ndn_message.FaceEventNotificationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_event_notification', full_name='ndn_message.FaceEventNotificationMessage.face_event_notification', index=0,
      number=192, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FACEEVENTNOTIFICATIONMESSAGE_FACEEVENTNOTIFICATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=378,
)

_FACEEVENTNOTIFICATIONMESSAGE_FACEEVENTNOTIFICATION.containing_type = _FACEEVENTNOTIFICATIONMESSAGE
_FACEEVENTNOTIFICATIONMESSAGE.fields_by_name['face_event_notification'].message_type = _FACEEVENTNOTIFICATIONMESSAGE_FACEEVENTNOTIFICATION
DESCRIPTOR.message_types_by_name['Name'] = _NAME
DESCRIPTOR.message_types_by_name['FaceEventNotificationMessage'] = _FACEEVENTNOTIFICATIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), dict(
  DESCRIPTOR = _NAME,
  __module__ = 'nfd_face_mgmt_pb2'
  # @@protoc_insertion_point(class_scope:ndn_message.Name)
  ))
_sym_db.RegisterMessage(Name)

FaceEventNotificationMessage = _reflection.GeneratedProtocolMessageType('FaceEventNotificationMessage', (_message.Message,), dict(

  FaceEventNotification = _reflection.GeneratedProtocolMessageType('FaceEventNotification', (_message.Message,), dict(
    DESCRIPTOR = _FACEEVENTNOTIFICATIONMESSAGE_FACEEVENTNOTIFICATION,
    __module__ = 'nfd_face_mgmt_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.FaceEventNotificationMessage.FaceEventNotification)
    ))
  ,
  DESCRIPTOR = _FACEEVENTNOTIFICATIONMESSAGE,
  __module__ = 'nfd_face_mgmt_pb2'
  # @@protoc_insertion_point(class_scope:ndn_message.FaceEventNotificationMessage)
  ))
_sym_db.RegisterMessage(FaceEventNotificationMessage)
_sym_db.RegisterMessage(FaceEventNotificationMessage.FaceEventNotification)


# @@protoc_insertion_point(module_scope)
